name: Playwright Test

on:
  push:
    branches:
      - main  # Mude para a branch principal do seu projeto ou o nome correto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Escolha a versão do Node.js que você deseja

      - name: Instalar Playwright
        run: |
          npm install -g playwright@1.38.0

      - name: Instalar dependências
        run: |
          npm install

      - name: Executar testes Playwright
        run: |
          npm run test-headless